# ====================== Directories ======================
paths:
  output_dir_models: "artifacts/models"  # directory where the trained model will be saved
  output_dir_data: "data/processed"  # directory where the processed data will be saved

# ====================== Data ======================
data:
  test_size: 0.2
  random_state: 42

# ====================== Grid Search ======================
gridCV:
  cv: 5
  n_jobs: -1
  verbose: 0

# ====================== Model Registry ======================
models:
  logistic_regression:
    class: "sklearn.linear_model.LogisticRegression"
    params:
      max_iter: 1000
      random_state: 42
    param_grid:
      model__C: [0.001, 0.01, 0.1, 1, 10, 100]
      model__penalty: ["l1", "l2"]
      model__solver: ["liblinear", "saga"]
      model__class_weight: [null, "balanced"]

  xgb_regressor:
    class: "xgboost.XGBClassifier"   # or XGBRegressor
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
      random_state: 42
    param_grid:
      model__n_estimators: [100, 200, 300]
      model__learning_rate: [0.01, 0.05, 0.1, 0.2]
      model__max_depth: [3, 5, 7]

  random_forest:
    class: "sklearn.ensemble.RandomForestClassifier"   # or Regressor
    params:
      random_state: 42
    param_grid:
      model__n_estimators: [100, 200, 300]
      model__max_depth: [null, 10, 20, 30]

  knn:
    class: "sklearn.neighbors.KNeighborsClassifier"   # or Regressor
    params:
      metric: 'minkowski'
    param_grid:
      model__n_neighbors: [3, 5, 7, 9]
      model__weights: ["uniform", "distance"]
      model__algorithm: ["auto", "ball_tree", "kd_tree", "brute"]
  
  lightgbm:
    class: "lightgbm.LGBMClassifier"   # or LGBMRegressor
    params:
      random_state: 42
    param_grid:
      model__n_estimators: [100, 200, 300]
      model__learning_rate: [0.01, 0.05, 0.1, 0.2]
      model__max_depth: [-1, 3, 5, 7]

  svm:
    class: "sklearn.svm.SVC"   # or SVR
    params:
      random_state: 42
      kernel: "linear"
    param_grid:
      model__C: [0.1, 1, 10, 100]